TILE_SIZE = 32
GRID_WIDTH = 10
GRID_HEIGHT = 20

GAME_WIDTH = GRID_WIDTH * TILE_SIZE
GAME_HEIGHT = GRID_HEIGHT * TILE_SIZE
SIDEBAR_WIDTH = 200

SCREEN_WIDTH = GAME_WIDTH + SIDEBAR_WIDTH
SCREEN_HEIGHT = GAME_HEIGHT
FPS = 60

STARTING_LEVEL = 1
LINES_TO_LEVEL_UP = 10
INITIAL_FALL_SPEED = 1000  
MIN_FALL_SPEED = 100       
SPEED_DECREMENT_RATIO = 0.8

SCORE_TABLE = {
    1: 100,  
    2: 300,   
    3: 500,   
    4: 800   
}

COMBO_BONUS = 50
B2B_MULTIPLIER = 1.5

TETROMINO_ASSETS = {
    'I': 'cyan.png',
    'J': 'blue.png',
    'L': 'orange.png',
    'O': 'yellow.png',
    'S': 'green.png',
    'T': 'purple.png',
    'Z': 'red.png'
}