name: Build and Release

on:
  push:
    branches:
      - 'release/v*'

jobs:
  build:
    name: Build & Package ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            artifact_name: linux
          - os: windows-latest
            artifact_name: windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create .env file from Secrets
        shell: bash
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pymongo python-dotenv cryptography certifi pyinstaller

      - name: Install nFPM
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          VERSION=v2.37.1
          curl -fL https://github.com/goreleaser/nfpm/releases/download/${VERSION}/nfpm_${VERSION#v}_amd64.deb -o nfpm.deb
          sudo dpkg -i nfpm.deb
          nfpm --version

      - name: Set VERSION
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/heads/release/v}" >> $GITHUB_ENV

      - name: Build executable
        run: make build

      - name: Package
        run: make package VERSION=${{ env.VERSION }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            *.exe
            *.deb
            *.rpm

  create_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get version from branch
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/heads/release/v}" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Bloquinhos - v${{ env.VERSION }}
          generate_release_notes: true
          body: |
            ## 🎮 Como Jogar

            ### 🪟 Windows
            1. Baixe o `.exe`.
            2. Clique com o botão direito → Propriedades → Desbloquear.
            3. Execute o instalador.

            ### 🐧 Linux
            1. Baixe o `.deb` ou `.rpm`.
            2. Instale via terminal:
               ```bash
               sudo apt install ./bloquinhos-linux.deb
               sudo dnf install bloquinhos-linux.rpm
               ```
          files: |
            windows/*.exe
            linux/*.deb
            linux/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Release Branch
        if: success()
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ github.ref_name }}